# Generated by Django 5.2.4 on 2025-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/alumni/')),
            ],
        ),
        migrations.CreateModel(
            name='LabHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('google_scholar', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('orcid', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/lab_head/')),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/lab_members/')),
            ],
        ),
    ]
