# Generated by Django 5.2.4 on 2025-08-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alumni_labhead_labmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='labhead',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
