# Generated by Django 5.2.4 on 2025-08-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labhead_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_images/')),
                ('text', models.TextField()),
                ('caption', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
