# Generated by Django 5.2.4 on 2025-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_journalentry_journalmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
