# Generated by Django 5.2.4 on 2025-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_bookchapter_patent_trademark_rename_patents_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='labmember',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
