# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_labimage_labmember_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('embed_code', models.TextField(help_text='Paste the raw embed HTML code here')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
