# Generated by Django 5.2.4 on 2025-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_socialembed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('embed_code', models.TextField(help_text='Paste the raw embed HTML code here')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('embed_code', models.TextField(help_text='Paste the raw embed HTML code here')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialEmbed',
        ),
    ]
