# Generated by Django 5.2.4 on 2025-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_linkedinembed_twitterembed_delete_socialembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='hyperlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
